# Generated by Django 5.0 on 2025-07-21 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dateOpened', models.DateField(default=django.utils.timezone.now)),
                ('restaurantType', models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('eastern_european', 'Eastern European'), ('french', 'French'), ('fast_food', 'Fast Food')], max_length=100)),
                ('nick_name', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('expenditures', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurants')),
            ],
        ),
    ]
