# Generated by Django 5.0 on 2026-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingrediences',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredience',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('east_london', 'East London'), ('south_london', 'South Lo ndon'), ('north_london', 'North London'), ('west_london', 'West London')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Ingredience',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
