# Generated by Django 5.0 on 2025-08-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'ordering': ['capacity']},
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='items',
            field=models.ManyToManyField(to='app.menu'),
        ),
    ]
