# Generated by Django 5.0 on 2025-12-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_restaurants_options_alter_customerorder_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantfinance',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='shiftmanager',
            name='staff',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='RestaurantFinance',
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ShiftManager',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
