# Generated by Django 5.0 on 2026-03-30 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_menuitem_ingrediences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='size',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_reservation', models.CharField(max_length=200)),
                ('number_of_people', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.restaurant')),
            ],
        ),
    ]
