# Generated by Django 5.0 on 2025-07-28 20:33

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_staff_rename_dateopened_restaurants_date_opened_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]