# Generated by Django 5.0 on 2026-03-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_restaurant_size_reservation'),
    ]

    operations = [
    ]
