# Generated by Django 5.0 on 2026-04-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shift_duration_hours_shift_earnings_shift_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name_of_reservation'), name='unique_reservation_per_restaurant'),
        ),
    ]
