# Generated by Django 5.0 on 2026-04-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reservation_unique_reservation_per_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_people',
        ),
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='kids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='teens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
