# Generated by Django 5.0 on 2025-12-18 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Desert'), ('drink', 'Drink'), ('snack', 'Snack')], default='main', max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity_in_stock', models.IntegerField()),
                ('units', models.CharField(choices=[('kg', 'Kilograms'), ('mg', 'Miligrams'), ('g', 'Grams'), ('l', 'Liters')], max_length=5)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediences', to='app.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredience', models.ManyToManyField(to='app.ingredience')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='app.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('date_opened', models.DateField()),
                ('location', models.CharField(choices=[('east_london', 'East London'), ('south_london', 'South London'), ('north_london', 'North London'), ('west_london', 'West London')], max_length=200)),
                ('restaurant_cuisine', models.CharField(choices=[('italian', 'Italian'), ('indian', 'Indian'), ('british', 'British'), ('spanish', 'Spanish'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean')], max_length=200)),
                ('size', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='app.restaurant'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('date_employed', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_right', models.CharField(choices=[('temp_visa', 'Temp Visa'), ('student_visa', 'Student Visa'), ('eu_passport', 'EU Passport'), ('uk_passport', 'UK Passport')], max_length=200)),
                ('position', models.CharField(choices=[('chief', 'Chief'), ('waiter', 'Waiter'), ('manager', 'Manager')], default='waiter', max_length=200)),
                ('pay_per_hour', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_works_here', to='app.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='app.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
