# Generated by Django 6.0.4 on 2026-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_reservation_number_of_people_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_reservation_per_restaurant',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('east_london', 'East London'), ('south_london', 'South London'), ('north_london', 'North London'), ('west_london', 'West London')], max_length=200),
        ),
    ]
