# Generated by Django 6.0.4 on 2026-05-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_reservation_unique_reservation_per_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='unique_menu_item_per_restaurant',
        ),
    ]
