# Generated by Django 6.0.4 on 2026-06-12 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_menuitem_unique_menu_item_per_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
