# Generated by Django 5.0 on 2026-01-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_menuitem_unique_menu_item_per_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restaurant',
            name='capacity_gte_size',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_cuisine',
            field=models.CharField(choices=[('fast_food', 'Fast Food'), ('italian', 'Italian'), ('indian', 'Indian'), ('british', 'British'), ('spanish', 'Spanish'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean')], max_length=200),
        ),
    ]
