# Generated by Django 6.0.4 on 2026-06-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_menuitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Desert'), ('drink', 'Drink'), ('snack', 'Snack'), ('side', 'Side')], default='main', max_length=50),
        ),
    ]
