# Generated by Django 6.0.4 on 2026-07-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='date_employed',
            new_name='date_time_employed',
        ),
    ]
