# Generated by Django 6.0.4 on 2026-07-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_date_employed_staff_date_time_employed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'permissions': [('archive_restaurant', 'Can archive restaurant')]},
        ),
    ]
