# Generated by Django 6.0.4 on 2026-07-30 15:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_restaurant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='number_of_tables',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_of_order', models.DateTimeField(default=datetime.datetime(2026, 7, 30, 15, 11, 21, 25797, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('not_been_served', 'Not served'), ('waiting', 'Waiting'), ('complete', 'Complete')], max_length=100)),
                ('note', models.TextField(blank=True, max_length=400, null=True)),
                ('table_number', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.reservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.restaurant')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_taken', to='app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_sold_at', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order')),
            ],
        ),
    ]
