# Generated by Django 6.0.4 on 2026-08-07 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_restaurant_number_of_tables_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Desert'), ('drink', 'Drink'), ('snack', 'Snack')], default='main', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time_of_order',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_been_served', 'Not served'), ('waiting', 'Waiting'), ('complete', 'Complete')], default='not_been_served', max_length=100),
        ),
    ]
