# Generated by Django 6.0.4 on 2026-08-07 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 7, 14, 56, 53, 450778, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 7, 14, 58, 27, 998052, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
